name: Test Github Action
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: test.tex
          working_directory: test/
      - name: Compile LaTeX document with math symbols
        uses: ./
        with:
          root_file: math.tex
          working_directory: test/
      - name: Compile LaTeX document with biblatex/biber
        uses: ./
        with:
          root_file: biblatex.tex
          working_directory: test/
          extra_packages: biblatex-ieee
      - name: Compile LaTeX document with minted
        uses: ./
        with:
          root_file: minted.tex
          working_directory: test/
          extra_system_packages: py-pygments
          args: "-pdf -shell-escape -file-line-error -interaction=nonstopmode"
      - name: Compile LaTeX document with arara and graphviz
        uses: ./
        with:
          root_file: graphviz.tex
          working_directory: test/
          extra_packages: arara
          # openjdk11 is used by arara
          # ttf-freefont is used by graphviz.
          extra_system_packages: "graphviz openjdk11-jre ttf-freefont"
          compiler: arara
          args: "--verbose"
      - name: Check pdf files
        run: |
          set -e
          file test/test.pdf | grep -q ' PDF '
          file test/math.pdf | grep -q ' PDF '
          file test/biblatex.pdf | grep -q ' PDF '
          file test/minted.pdf | grep -q ' PDF '
          file test/graphviz.pdf | grep -q ' PDF '
          file test/abc.pdf | grep -q ' PDF '
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: test
          path: test
        if: always()
